import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "@/assets/styles/globals.scss";
import { ViewTransitions } from "next-view-transitions";

export const metadata: Metadata = {
    title      : "Create Next App",
    description: "Generated by create next app"
};

type RootLayoutProps = {
    children: ReactNode;
}

export default function RootLayout({children}: RootLayoutProps) {
    return (
        <ViewTransitions>
            <html lang="en">
            <body>
                <Header/>

                <main>
                    {children}
                </main>

                <Footer/>
            </body>
            </html>
        </ViewTransitions>
    );
}